config/routes.rb
AutoMonitoring::Application.routes.draw do

  namespace :api do
    resources :employees

    resources :companies do
      scope :module => :companies do
        resources :people, :only => [:index]
        resources :deals, :only => [:index]
        resources :counteragents, :only => [:index]
      end
    end

    resources :employee_positions, :only => [] do
      scope :module => :employee_positions do
        resources :privileges, :only => [:index]
      end
    end

    resources :product_items, :only =>[:show]

    resources :companies_tags, :only => [] do
      get :autocomplete, :on => :collection
    end

    resources :phones, :only => [] do
      get :exists, :on => :collection
    end

    resources :emails, :only => [] do
      get :exists, :on => :collection
    end

    resources :current_month_payment, :only => [] do
      get :month_number, :on => :collection
    end

    resources :search, :only => [:index]
  end

  scope :module => 'web' do
    root :to => 'welcome#index'

    namespace :admin do
      root :to => 'employees#index'
      resources :employees, :only => [:index, :show, :new, :create, :edit, :update] do
        put :trigger_state_event, :on => :member
      end
      resources :employees_departments
      resources :employees_positions
      resources :companies_categories
      resources :companies_statuses
      resources :juridical_people
    end

    namespace :employee do
      root :to => 'companies#index'

      resources :companies_people do
        scope :module => :companies_people do
          resources :notes, :only => [:create]
        end
      end

      resources :companies_invoices, :only => [:index, :new, :create, :edit, :update] do
        scope :module => :companies_invoices do
          resources :notes, :only => [:create]
        end
      end

      resources :companies do
        scope :module => :companies do
          resources :notes, :only => [:create]
          resources :people, :only => [:show]
          resources :invoices, :only => [:show] do
            put :trigger_state_event, :on => :member
          end
          resources :deals, :only => [:show]
        end
      end
      resources :companies_accounts, :only => [:index, :destroy]
      resources :companies_crm_accounts
      resources :companies_gis_accounts
      resources :companies_invoices
      resources :companies_deals
      resources :tariffs
      resources :events
      resources :product_items
      resource :session, :only => [:new, :create, :destroy]
      resources :search, :only => [:index]
    end

    namespace :company do
      root :to => 'deals#index'
      resources :deals, :only => [:index, :show]
      resources :invoices, :only => [:index, :show]
      resources :accounts
      resources :crm_accounts
      resources :gis_accounts
      resource :session, :only => [:new, :create, :destroy]
    end
  end
end

app/controllers/web/admin/companies_statuses_controller.rb
class Web::Admin::CompaniesStatusesController < Web::Admin::ProtectedApplicationController
  add_i18n_breadcrumb :index, :admin_companies_statuses_path

  def index
    title t(:companies_statuses)

    params[:search] = {:meta_sort => 'id.asc'}.merge(params[:search] || {})
    @search = ::Company::Status.metasearch(params[:search])
    @companies_statuses = @search.page(params[:page]).per(params[:per_page])
  end

  def new
    @company_status = ::Company::Status.new

    add_i18n_breadcrumb :new, :new_admin_companies_status_path
  end

  def create
    @company_status = ::Company::Status.new(params[:company_status])

    if @company_status.save
      flash[:success] = flash_translate(:success)
      redirect_to :action => :index
    else
      add_i18n_breadcrumb :new, :new_admin_companies_status_path
      render :action => :new
    end
  end

  def edit
    @company_status = ::Company::Status.find(params[:id])

    add_breadcrumb @company_status, :edit_admin_companies_status_path
  end

  def update
    @company_status = ::Company::Status.find(params[:id])

    add_breadcrumb @company_status.name, :edit_admin_companies_status_path

    if @company_status.update_attributes(params[:company_status])
      flash[:success] = flash_translate(:success)
      redirect_to :action => :index
    else
      render :action => :edit
    end
  end

  def destroy
    @company_status = ::Company::Status.find(params[:id])
    @company_status.destroy

    redirect_to :action => :index
  end
end

app/helpers/web/admin/companies_statuses_helper.rb
module Web::Admin::CompaniesStatusesHelper
end

app/views/web/admin/companies_statuses/_form.html.haml
= simple_form_for @company_status, :url => url, :html => {:class => "form-horizontal"} do |f|
  %legend= legend
  = f.error_notification
  = f.input :name
  = f.input :color, :input_html => {:class => 'color'}
  .form-actions
    = f.button :submit, :class => "btn btn-primary"
    = link_to t(:cancel), admin_companies_statuses_path, :class => "btn"
    - if @company_status.persisted?
      = link_to t(".delete_company_status"), admin_companies_status_path(@company_status),
        :method => :delete, :confirm => t(:sure), :class => "btn btn-danger" unless @company_status.our_client?

app/views/web/admin/companies_statuses/edit.html.haml
.span6
  = render 'form', {:url => admin_companies_status_path(@company_status), :legend => t(".edit_company_status")}

app/views/web/admin/companies_statuses/index.html.haml
= content_for :list_title do
  %h3= t('.title')
  %p

%table.table.table-striped
  %thead
    %tr
      %th= sort_link @search, :id
      %th= sort_link @search, :name, Company::Status.human_attribute_name('name')
      %th
  %tbody
    - @companies_statuses.each do |c|
      %tr
        %td= c.id
        %td= content_tag(:span, c.name, { :class => 'label', :style => "background-color: ##{c.color}"})
        %td
          %span
            %a{:href => edit_admin_companies_status_path(c), :title => t(:edit)}
              %i.icon-edit
          - unless c.our_client?
            %span
              %a{:href => admin_companies_status_path(c), :data => {:method => :delete, :confirm => t(:sure)}, :title => t(:delete)}
                %i.icon-remove
.form-actions
  = render "web/shared/toolbar", {:collection => @companies_statuses, :buttons => [{:link_title => t('.add_company_status'), :link_path => new_admin_companies_status_path}]}

app/views/web/admin/companies_statuses/new.html.haml
.span6
  = render 'form', {:url => admin_companies_statuses_path, :legend => t(".new_company_status")}