config/routes.rb
AutoMonitoring::Application.routes.draw do

  namespace :api do
    resources :employees

    resources :companies do
      scope :module => :companies do
        resources :people, :only => [:index]
        resources :deals, :only => [:index]
        resources :counteragents, :only => [:index]
      end
    end

    resources :employee_positions, :only => [] do
      scope :module => :employee_positions do
        resources :privileges, :only => [:index]
      end
    end

    resources :product_items, :only =>[:show]

    resources :companies_tags, :only => [] do
      get :autocomplete, :on => :collection
    end

    resources :phones, :only => [] do
      get :exists, :on => :collection
    end

    resources :emails, :only => [] do
      get :exists, :on => :collection
    end

    resources :current_month_payment, :only => [] do
      get :month_number, :on => :collection
    end

    resources :search, :only => [:index]
  end

  scope :module => 'web' do
    root :to => 'welcome#index'

    namespace :admin do
      root :to => 'employees#index'
      resources :employees, :only => [:index, :show, :new, :create, :edit, :update] do
        put :trigger_state_event, :on => :member
      end
      resources :employees_departments
      resources :employees_positions
      resources :companies_categories
      resources :companies_statuses
      resources :juridical_people
    end

    namespace :employee do
      root :to => 'companies#index'

      resources :companies_people do
        scope :module => :companies_people do
          resources :notes, :only => [:create]
        end
      end

      resources :companies_invoices, :only => [:index, :new, :create, :edit, :update] do
        scope :module => :companies_invoices do
          resources :notes, :only => [:create]
        end
      end

      resources :companies do
        scope :module => :companies do
          resources :notes, :only => [:create]
          resources :people, :only => [:show]
          resources :invoices, :only => [:show] do
            put :trigger_state_event, :on => :member
          end
          resources :deals, :only => [:show]
        end
      end
      resources :companies_accounts, :only => [:index, :destroy]
      resources :companies_crm_accounts
      resources :companies_gis_accounts
      resources :companies_invoices
      resources :companies_deals
      resources :tariffs
      resources :events
      resources :product_items
      resource :session, :only => [:new, :create, :destroy]
      resources :search, :only => [:index]
    end

    namespace :company do
      root :to => 'deals#index'
      resources :deals, :only => [:index, :show]
      resources :invoices, :only => [:index, :show]
      resources :accounts
      resources :crm_accounts
      resources :gis_accounts
      resource :session, :only => [:new, :create, :destroy]
    end
  end
end

app/controllers/web/admin/juridical_people_controller.rb
class Web::Admin::JuridicalPeopleController < Web::Admin::ProtectedApplicationController
  add_i18n_breadcrumb :index, :admin_juridical_people_path

  def index
    title t(:juridical_people)

    params[:search] = {:meta_sort => 'created_at.asc'}.merge(params[:search] || {})
    @search = ::JuridicalPerson.metasearch(params[:search])
    @juridical_people = @search.page(params[:page]).per(params[:per_page])
  end

  def new
    @juridical_person = ::JuridicalPerson.new

    add_i18n_breadcrumb :new, :new_admin_juridical_person_path
  end

  def edit
    @juridical_person = ::JuridicalPerson.find(params[:id])

    add_breadcrumb @juridical_person, :edit_admin_juridical_person_path
  end

  def create
    @juridical_person = ::JuridicalPerson.new(params[:juridical_person])

    if @juridical_person.save
      flash[:success] = flash_translate(:success)
      redirect_to :action => :index
    else
      add_i18n_breadcrumb :new, :new_admin_juridical_person_path
      render :action => :new
    end
  end

  def update
    @juridical_person = ::JuridicalPerson.find(params[:id])

    add_breadcrumb @juridical_person, :edit_admin_juridical_person_path

    if @juridical_person.update_attributes(params[:juridical_person])
      flash[:success] = flash_translate(:success)
      redirect_to :action => :index
    else
      render :action => :edit
    end
  end

  def destroy
    @juridical_person = ::JuridicalPerson.find(params[:id])
    @juridical_person.destroy

    redirect_to :action => :index
  end
end

app/helpers/web/admin/juridical_people_helper.rb
module Web::Admin::JuridicalPeopleHelper
end

app/views/web/admin/juridical_people/_detail_fields.html.haml
%div{class: "control-group nested-fields #{error_class(f.object)}"}
  .controls
    = f.select :kind_id,
      options_from_collection_for_select(juridical_person_detail_kinds, :id, :to_s, f.object.kind_id),
      { :include_blank => true },
      { :class => 'input-small' }
    = f.input_field :value
    .close
      = link_to_remove_association 'x', f, {:class => 'btn btn-danger disabled'}
    = f.error :kind_id
    = f.error :value

app/views/web/admin/juridical_people/_form.html.haml
= simple_form_for @juridical_person, :url => url, :html => {:class => "form-horizontal"} do |f|
  %legend= legend
  = f.error_notification
  = f.input :name
  = f.input :invoice_number_prefix
  = f.simple_fields_for :details do |detail|
    = render 'detail_fields', :f => detail
  .links.control-group
    .controls
      = link_to_add_association t('.add_detail'), f, :details, {:class => 'btn btn-small btn-info'}
  .form-actions
    = f.button :submit, :class => 'btn btn-primary'
    = link_to t(:cancel), admin_juridical_people_path, :class => 'btn'
    - if @juridical_person.persisted?
      = link_to t('.delete_juridical_person'), admin_juridical_person_path(@juridical_person),
        :method => :delete, :confirm => t(:sure), :class => 'btn btn-danger'

app/views/web/admin/juridical_people/edit.html.haml
.span7
  = render 'form', {:url => admin_juridical_person_path(@juridical_person), :legend => t('.edit_juridical_person')}

app/views/web/admin/juridical_people/index.html.haml
= content_for :list_title do
  %h3= t('.title')
  %p

%table.table.table-striped
  %thead
    %tr
      %th= sort_link @search, :id
      %th= sort_link @search, :name
      %th= sort_link @search, :invoice_number_prefix
      %th= JuridicalPerson.human_attribute_name('details')
      %th= sort_link @search, :created_at
      %th
  %tbody
    - @juridical_people.each do |p|
      %tr
        %td= p.id
        %td= p.name
        %td= p.invoice_number_prefix
        %td
          - if p.details.present?
            %ul
              - p.details.each do |d|
                %li= "#{d.kind}: #{d}"
        %td= l p.created_at, :format => :only_date
        %td
          %span
            %a{:href => edit_admin_juridical_person_path(p), :title => t(:edit)}
              %i.icon-edit
          %span
            %a{:href => admin_juridical_person_path(p), :data => {:method => :delete, :confirm => t('.sure')}, :title => t(:delete)}
              %i.icon-remove
.form-actions
  = render "web/shared/toolbar", {:collection => @juridical_people, :buttons => [{:link_title => t('.add_juridical_person'), :link_path => new_admin_juridical_person_path}]}

app/views/web/admin/juridical_people/new.html.haml
.span6
  = render 'form', {:url => admin_juridical_people_path, :legend => t('.new_juridical_person')}