config/routes.rb
AutoMonitoring::Application.routes.draw do

  namespace :api do
    resources :employees

    resources :companies do
      scope :module => :companies do
        resources :people, :only => [:index]
        resources :deals, :only => [:index]
        resources :counteragents, :only => [:index]
      end
    end

    resources :employee_positions, :only => [] do
      scope :module => :employee_positions do
        resources :privileges, :only => [:index]
      end
    end

    resources :product_items, :only =>[:show]

    resources :companies_tags, :only => [] do
      get :autocomplete, :on => :collection
    end

    resources :phones, :only => [] do
      get :exists, :on => :collection
    end

    resources :emails, :only => [] do
      get :exists, :on => :collection
    end

    resources :current_month_payment, :only => [] do
      get :month_number, :on => :collection
    end

    resources :search, :only => [:index]
  end

  scope :module => 'web' do
    root :to => 'welcome#index'

    namespace :admin do
      root :to => 'employees#index'
      resources :employees, :only => [:index, :show, :new, :create, :edit, :update] do
        put :trigger_state_event, :on => :member
      end
      resources :employees_departments
      resources :employees_positions
      resources :companies_categories
      resources :companies_statuses
      resources :juridical_people
    end

    namespace :employee do
      root :to => 'companies#index'

      resources :companies_people do
        scope :module => :companies_people do
          resources :notes, :only => [:create]
        end
      end

      resources :companies_invoices, :only => [:index, :new, :create, :edit, :update] do
        scope :module => :companies_invoices do
          resources :notes, :only => [:create]
        end
      end

      resources :companies do
        scope :module => :companies do
          resources :notes, :only => [:create]
          resources :people, :only => [:show]
          resources :invoices, :only => [:show] do
            put :trigger_state_event, :on => :member
          end
          resources :deals, :only => [:show]
        end
      end
      resources :companies_accounts, :only => [:index, :destroy]
      resources :companies_crm_accounts
      resources :companies_gis_accounts
      resources :companies_invoices
      resources :companies_deals
      resources :tariffs
      resources :events
      resources :product_items
      resource :session, :only => [:new, :create, :destroy]
      resources :search, :only => [:index]
    end

    namespace :company do
      root :to => 'deals#index'
      resources :deals, :only => [:index, :show]
      resources :invoices, :only => [:index, :show]
      resources :accounts
      resources :crm_accounts
      resources :gis_accounts
      resource :session, :only => [:new, :create, :destroy]
    end
  end
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  include EmployeeRepository
  has_secure_password

  attr_accessible :email, :password, :first_name, :last_name, :patronymic, :position_id, :privilege_ids

  belongs_to :position

  has_many :events, :dependent => :destroy
  has_many :company_person_notes, :class_name => 'Company::Person::Note', :dependent => :destroy
  has_many :company_invoice_notes, :class_name => 'Company::Invoice::Note', :dependent => :destroy
  has_many :company_notes, :class_name => 'Company::Note', :dependent => :destroy
  has_many :employee_credentials, :dependent => :destroy
  has_many :privileges, :through => :employee_credentials
  has_many :accounts, :as => :creator

  validates :email, :presence => true, :email => true, :uniqueness => {:case_sensitive => false}
  validates :first_name, :presence => true, :length => {:maximum => 256}
  validates :last_name, :presence => true, :length => {:maximum => 256}
  validates :patronymic, :length => {:maximum => 256}

  state_machine :state, :initial => :active do
    state :active
    state :deleted

    event :activate do
      transition any - :active => :active
    end

    event :del do
      transition any - :deleted => :deleted
    end
  end

  def can?(name)
    privilege = Privilege.find_by_key(name)
    if privilege
      privileges.include?(privilege)
    else
      raise Privilege::NotFoundError, "Privilege with name #{name} not found."
    end
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def to_s
    full_name
  end
end

app/models/employee/department.rb
class Employee::Department < ActiveRecord::Base
  attr_accessible :name, :positions_attributes

  has_many :employees
  has_many :positions, :dependent => :destroy

  validates :name, :presence => true, :length => {:maximum => 256}

  accepts_nested_attributes_for :positions, :reject_if => :all_blank, :allow_destroy => true

  state_machine :state, :initial => :active do
    state :active
  end

  def to_s
    name
  end
end

app/models/employee/event.rb
class Employee::Event < ActiveRecord::Base
  include EventRepository

  attr_accessible :description, :due_date, :company_id, :company_person_id

  belongs_to :creator, :class_name => ::Employee, :foreign_key => 'employee_id'
  belongs_to :company_person, :class_name => ::Company::Person, :foreign_key => 'company_person_id'
  belongs_to :company

  validates :creator, :presence => true
  validates :company, :presence => true
  validates :description, :presence => true, :length => {:maximum => 100}
  validates :due_date, :presence => true

  state_machine :state, :initial => :new do
    state :new
  end

  def description_short
    description.truncate(40)
  end
end

app/models/employee/position.rb
class Employee::Position < ActiveRecord::Base
  include PositionRepository
  attr_accessible :name, :department_id, :privilege_ids

  belongs_to :department

  has_many :employees
  has_many :position_privileges, :dependent => :destroy
  has_many :privileges, :through => :position_privileges

  validates :name, :presence => true, :length => {:maximum => 256}

  state_machine :state, :initial => :active do
    state :active
  end

  def to_s
    name
  end
end

app/models/employee/position_privilege.rb
class Employee::PositionPrivilege < ActiveRecord::Base
  attr_accessible :position_id, :privilege_id

  belongs_to :position
  belongs_to :privilege
end

app/models/employee/privilege.rb
class Employee::Privilege < ActiveRecord::Base
  attr_accessible :key, :name, :kind

  belongs_to :kind

  has_many :employee_credentials
  has_many :employees, :through => :employee_credentials
  has_many :position_privileges
  has_many :positions, :through => :position_privileges

  validates :name, :presence => true, :length => {:maximum => 255}
  validates :key, :slug => true, :uniqueness => true
  validates :kind, :presence => true
end

app/models/employee/privilege/access_denied_error.rb
class Employee::Privilege::AccessDeniedError < StandardError
end

app/models/employee/privilege/kind.rb
class Employee::Privilege::Kind < ActiveRecord::Base
  include UsefullScopes

  attr_accessible :name

  has_many :privileges

  validates :name, :presence => true, :uniqueness => {:case_sensitive => false},
            :length => {:maximum => 255}

  def to_s
    name
  end
end

app/models/employee/privilege/not_found_error.rb
class Employee::Privilege::NotFoundError < StandardError
end

app/models/employee/privilege/object_access_denied_error.rb
class Employee::Privilege::ObjectAccessDeniedError < StandardError
  attr_reader :record
  def initialize(message_error, record)
    @record = record
    super(message_error)
  end
end

app/controllers/api/employees_controller.rb
class Api::EmployeesController < Api::ApplicationController
  def update
    @employee = ::Employee.find(params[:id])
    @employee.update_attributes!(params[:employee])
    respond_with(@employee)
  end

  def show
    @employee = ::Employee.find(params[:id])
    respond_with(@employee)
  end
end

app/controllers/web/admin/employees_controller.rb
class Web::Admin::EmployeesController < Web::Admin::ProtectedApplicationController
  add_i18n_breadcrumb :index, :admin_employees_path

  def index
    title t(:employees)

    params[:search] = {:meta_sort => 'id.asc'}.merge(params[:search] || {})
    @search = ::Employee.metasearch(params[:search])
    @employees = @search.page(params[:page]).per(params[:per_page])
  end

  def new
    @employee = NewEmployeeType.new

    add_i18n_breadcrumb :new, :new_admin_employee_path
  end

  def show
    @employee = ::Employee.find(params[:id])

    add_breadcrumb @employee, :admin_employee_path
  end

  def edit
    @employee = ::Employee.find(params[:id])

    add_breadcrumb @employee, :edit_admin_employee_path
  end

  def create
    @employee = NewEmployeeType.new(params[:employee])

    if @employee.save
      flash[:success] = flash_translate(:success)
      redirect_to :action => :index
    else
      add_i18n_breadcrumb :new, :new_admin_employee_path
      render :action => :new
    end
  end

  def update
    @employee = ::Employee.find(params[:id])

    add_breadcrumb @employee.full_name, :edit_admin_employee_path

    if @employee.update_attributes(params[:employee])
      flash[:success] = flash_translate(:success)
      redirect_to :action => :index
    else
      render :action => :edit
    end
  end

  def trigger_state_event
    @employee = ::Employee.find(params[:id])
    @employee.fire_state_event(params[:event])

    redirect_to :action => :index
  end
end

app/controllers/web/employee/application_controller.rb
class Web::Employee::ApplicationController < Web::ApplicationController
  layout 'web/employee/application'

  before_filter :employee_title
  helper_method :employee_signed_in?, :current_employee, :permission,
                :employee_constraints

  private

  def employee_title
    title t("title.employee")
  end

  rescue_from ::Employee::Privilege::ObjectAccessDeniedError do |e|
    flash[:error] = flash_translate(:error, :assigned => e.record.is_a?(::Company) ? e.record.assigned : e.record.company.assigned)
    redirect_to employee_root_path
  end

  rescue_from ::Employee::Privilege::AccessDeniedError do
    flash[:error] = flash_translate(:error)
    redirect_to employee_root_path
  end
end

app/controllers/web/employee/companies/application_controller.rb
class Web::Employee::Companies::ApplicationController < Web::Employee::ProtectedApplicationController
  before_filter do
    add_i18n_breadcrumb :general, :employee_companies_path
    add_breadcrumb current_company, employee_company_path(current_company)
  end

  def current_company
    scope = build_scope 'company'
    scope.get(params[:company_id])
  end
end

app/controllers/web/employee/companies/deals_controller.rb
class Web::Employee::Companies::DealsController < Web::Employee::Companies::ApplicationController
  def show
    scope_deals = build_scope 'company/deal'
    @company_deal = scope_deals.get(params[:id]).decorate
    scope_invoices = build_scope 'company/invoice'
    @invoices = Company::InvoiceDecorator.decorate(scope_invoices.find_all_by_deal_id(@company_deal.id))

    add_i18n_breadcrumb :index, employee_companies_deals_path({:search => {:company_id_equals => current_company.id}})
    add_breadcrumb @company_deal.deal_number, employee_company_deal_path(@company_deal.company, @company_deal)
  end
end

app/controllers/web/employee/companies/invoices_controller.rb
class Web::Employee::Companies::InvoicesController < Web::Employee::Companies::ApplicationController
  def show
    scope = build_scope 'company/invoice'
    @company_invoice = scope.get(params[:id]).decorate
    @invoice_product_items = Company::InvoiceProductItemDecorator.decorate(@company_invoice.invoice_product_items)
    @notes = @company_invoice.notes
    @note = current_employee.company_invoice_notes.build

    add_i18n_breadcrumb :index, employee_companies_invoices_path({:search => {:company_id_equals => current_company.id}})
    add_breadcrumb t('breadcrumbs.web.employee.companies.invoices.show', {:number => @company_invoice.invoice_number}), employee_company_invoice_path(@company_invoice.company, @company_invoice)
  end

  def trigger_state_event
    scope = build_scope 'company/invoice'
    @company_invoice = scope.get(params[:id])
    @company_invoice.fire_state_event(params[:event])

    redirect_to_from_params_or(employee_companies_invoices_path)
  end
end

app/controllers/web/employee/companies/notes_controller.rb
class Web::Employee::Companies::NotesController < Web::Employee::Companies::ApplicationController
  def create
    @company = current_company
    @note = @company.notes.build(params[:company_note])
    @note.creator = current_employee

    if @note.save
      flash[:success] = flash_translate(:success)
    else
      flash[:error] = flash_translate(:error)
    end

    redirect_to employee_company_path(@company)
  end
end

app/controllers/web/employee/companies/people_controller.rb
class Web::Employee::Companies::PeopleController < Web::Employee::Companies::ApplicationController
  def show
    scope = build_scope 'company/person'
    @company_person = scope.get(params[:id])
    @notes = @company_person.notes
    @note = current_employee.company_person_notes.build

    add_breadcrumb @company_person, employee_company_person_path(@company_person.company, @company_person)
  end
end

app/controllers/web/employee/companies_accounts_controller.rb
class Web::Employee::CompaniesAccountsController < Web::Employee::ProtectedApplicationController
  add_i18n_breadcrumb :general, :employee_companies_path
  def index
    title t(:companies_accounts)

    params[:search] = {:meta_sort => 'id.asc'}.merge(params[:search] || {})
    scope = build_scope 'company/account'
    @search = scope.accounts_list.metasearch(params[:search])
    @companies_accounts = @search.page(params[:page]).per(params[:per_page])
    @companies_accounts = Draper::DecoratedEnumerableProxy.new(@companies_accounts, Company::Account)
    add_i18n_breadcrumb :index, :employee_companies_accounts_path
  end

  def destroy
    scope = build_scope 'company/account'
    @company_account = scope.get(params[:id])
    @company_account.destroy
    redirect_to :action => :index
  end
end

app/controllers/web/employee/companies_controller.rb
class Web::Employee::CompaniesController < Web::Employee::ProtectedApplicationController
  add_i18n_breadcrumb :general, :employee_companies_path

  def index
    title t(:companies)

    params[:search] = {:meta_sort => 'id.asc'}.merge(params[:search] || {})
    scope = build_scope 'company'
    @search = scope.companies_list.metasearch(params[:search])
    @companies = CompanyDecorator.decorate(@search.page(params[:page]).per(params[:per_page]))
  end

  def new
    @company = ::Company.new
    @company.contact_details.build({ :kind_id => ContactDetail::Kind.phone.id })
    @company.contact_details.build({ :kind_id => ContactDetail::Kind.email.id })
    @company.assigned = current_employee

    add_i18n_breadcrumb :new, :new_employee_company_path
  end

  def show
    scope = build_scope 'company'
    @company = scope.get(params[:id]).decorate

    @notes = @company.notes
    @note = current_employee.company_notes.build
    @deals = Company::DealDecorator.decorate(@company.deals)
    @people = @company.people
    scope = build_scope 'company/invoice'
    invoices = Draper::DecoratedEnumerableProxy
      .new(scope.invoices_list.asc_by_created_at.find_all_by_company_id(@company.id),
           Company::Invoice)
      .decorated_collection
    @grouped_invoices = invoices.group_by &:deal_id

    add_breadcrumb @company, :employee_company_path
  end

  def create
    @company = ::Company.new(params[:company])
    @company.creator = current_employee

    if @company.save
      flash[:success] = flash_translate(:success)
      redirect_to :action => :show, :id => @company
    else
      add_i18n_breadcrumb :new, :new_employee_company_path
      render :action => :new
    end
  end

  def edit
    scope = build_scope 'company'
    @company = scope.get(params[:id])

    add_breadcrumb @company, :edit_employee_company_path
  end

  def update
    scope = build_scope 'company'
    @company = scope.get(params[:id])

    add_breadcrumb @company, :edit_employee_company_path

    if @company.update_attributes(params[:company])
      flash[:success] = flash_translate(:success)
      redirect_to :action => :show, :id => @company
    else
      render :action => :edit
    end
  end

  def destroy
    scope = build_scope 'company'

    if current_employee.can?(:company_delete)
      @company = scope.get(params[:id])
      @company.destroy
    else
      flash[:error] = flash_translate(:error)
    end

    redirect_to :action => :index
  end
end

app/views/web/employee/companies_invoices/_filter.html.haml
- content_for :filter do
  = simple_form_for :search, :url => employee_companies_invoices_path, :method => :get, :html => {:class => 'form-inline'} do |f|
    = f.collection_select :company_id_equals, companies, :id, :name, :include_blank => t('.choose_company')
    = f.collection_select :kind_id_equals, company_invoice_kinds, :id, :name, :include_blank => t('.choose_invoice_kind')
    = f.select :payment_state_equals, company_invoice_payment_states, :include_blank => t('.choose_invoice_payment_state')
    - if current_employee.can? :invoice_manage_all
      = f.select :state_equals, company_invoice_states, :include_blank => t('.choose_invoice_state')
    = f.button :submit, t('filter_panel.buttons.filter'), :class => 'btn btn-primary'
    = submit_tag t('filter_panel.buttons.reset'), :type => :reset, :class => 'btn'

app/views/web/employee/companies_invoices/_form.html.haml
= simple_form_for @company_invoice,:as => :company_invoice, :url => url, :html => {:class => "form-horizontal"} do |f|
  %legend= legend
  = f.error_notification
  .row-fluid.employee
    .span6
      %h4= t(".product_items")
      %p
      = f.simple_fields_for :invoice_product_items do |i|
        = render 'invoice_product_item_fields', :f => i
      .links.control-group
        = link_to_add_association t('.add_product_item'), f, :invoice_product_items, {:class => 'btn btn-small btn-info'}
      = f.input :amount, :readonly => true
      = f.input :equity_amount, :readonly => true
    .span5
      - if @company_invoice.persisted?
        .control-group.state
          = f.label :state
          .controls
            %span{:class => "label label-invoice-#{@company_invoice.state_name}"}= @company_invoice.human_state_name
      = f.input :expected_payment_date, :as => :string,
        :disabled => !EmployeeAccessController.can_setup_company_invoice_expected_payment_date?(current_employee, @company_invoice)
      = f.input :actual_payment_date, :as => :string,
        :disabled => !EmployeeAccessController.can_setup_company_invoice_actual_payment_date?(current_employee, @company_invoice)
      = f.input :old_type, :as => :hidden
      = f.association :company, :as => :chosen_select, :collection => companies,
        :include_blank => t('.choose_company')
      = f.association :deal, :collection => companies_deals_collection
      = f.association :kind, :include_blank => false
      = f.input :period_start_date, :as => :string
      = f.input :period_end_date, :as => :string
      = f.association :payment_method
      - if @company_invoice.unpaid?
        = f.input :payment_state_event, :as => :payment_state_event
      = f.input :documents_returned, :as => :boolean
  .form-actions
    = f.button :submit, :class => "btn btn-primary"
    - if @company_invoice.persisted?
      = link_to t(:cancel), employee_company_path(@company_invoice.company), :class => "btn"
      - if current_employee.can? :invoice_manage_all
        - if @company_invoice.can_activate?
          = link_to ::Company::Invoice.human_state_event_name(:activate),
            trigger_state_event_employee_company_invoice_path(@company_invoice.company,
              @company_invoice, {event: :activate, redirect_to: employee_company_path(@company_invoice.company)}),
            :method => :put, :confirm => t(:sure), :class => "btn btn-success"
        - if @company_invoice.can_archive?
          = link_to ::Company::Invoice.human_state_event_name(:archive),
            trigger_state_event_employee_company_invoice_path(@company_invoice.company,
              @company_invoice, {event: :archive, redirect_to: employee_company_path(@company_invoice.company)}),
            :method => :put, :confirm => t(:sure), :class => "btn btn-warning"
        - if @company_invoice.can_del?
          = link_to ::Company::Invoice.human_state_event_name(:del),
            trigger_state_event_employee_company_invoice_path(@company_invoice.company,
              @company_invoice, {event: :del, redirect_to: employee_company_path(@company_invoice.company)}),
            :method => :put, :confirm => t(:sure), :class => "btn btn-danger"
    - else
      = link_to t(:cancel), employee_companies_invoices_path, :class => "btn"

app/views/web/employee/companies_invoices/_invoice_product_item_fields.html.haml
.control-group.nested-fields.new_invoice_product_item
  = f.select :product_item_id, options_from_collection_for_select(product_items, :id, :to_s, f.object.product_item_id),
    { :include_blank => true },
    { :class => 'contact_detail_kind input-small' }
  = f.input_field :prime_amount, :class => 'input-prime-amount input-small', :placeholder => ::Company::InvoiceProductItem.human_attribute_name('prime_amount'), :readonly => true
  = f.input_field :sail_amount, :class => 'input-sail-amount input-small', :placeholder => ::Company::InvoiceProductItem.human_attribute_name('sail_amount')
  = f.input_field :product_items_count, :class => 'input-items-count input-small', :placeholder => ::Company::InvoiceProductItem.human_attribute_name('product_items_count')
  .close
    = link_to_remove_association 'x', f, {:class => 'btn btn-danger disabled'}
  = f.error :product_item_id
  = f.error :product_items_count
  = f.error :prime_amount
  = f.error :sail_amount

app/views/web/employee/companies_invoices/edit.html.haml
.span11
  = render 'form', {:url => employee_companies_invoice_path(@company_invoice), :legend => t(".edit_company_invoice", {:number => @company_invoice.invoice_number})}

app/views/web/employee/companies_invoices/index.html.haml
= content_for :list_title do
  %h3= t('.title')
  %p

= render 'filter'
%table.table
  %thead
    %tr
      %th= sort_link @search, :id
      %th= sort_link @search, :invoice_number
      %th= sort_link @search, :amount_in_kop, Company::Invoice.human_attribute_name('amount')
      %th= sort_link @search, :equity_amount_in_kop, Company::Invoice.human_attribute_name('equity_amount')
      %th= sort_link @search, :created_at
      %th= sort_link @search, :expected_payment_date
      %th= sort_link @search, :actual_payment_date
      %th= sort_link @search, :company_name, Company::Invoice.human_attribute_name('company')
      %th= sort_link @search, :deal_deal_number, Company::Invoice.human_attribute_name('deal')
      %th= sort_link @search, :kind_name, Company::Invoice.human_attribute_name('kind')
      %th= sort_link @search, :payment_method_name, Company::Invoice.human_attribute_name('payment_method')
      %th= sort_link @search, :payment_state_cache, Company::Invoice.human_attribute_name('payment_state')
      %th= sort_link @search, :documents_returned
      %th
  %tbody
    - @companies_invoices.each do |i|
      %tr
        - if i.notes.present?
          %td.row-invoice-id-valign{"rowspan" => 2}
            = i.id
        - else
          %td= i.id
        %td= link_to i.invoice_number, employee_company_invoice_path(i.company, i)
        %td= i.amount
        %td= i.equity_amount
        %td= l i.created_at, :format => :only_date
        %td= l i.expected_payment_date if i.expected_payment_date?
        %td= l i.actual_payment_date if i.actual_payment_date?
        %td= link_to i.company, employee_company_path(i.company), :title => i.company.name
        %td= link_to i.deal, employee_company_deal_path(i.deal.company, i.deal)
        %td= i.kind
        %td= i.payment_method
        %td
          %span{:class => "label label-invoice-#{i.payment_state_name}"}= i.human_payment_state_name
        %td= i.documents_returned ? t(:yes) : t(:no)
        %td
          %span
            %a{:href => edit_employee_companies_invoice_path(i), :title => t(:edit)}
              %i.icon-edit
          %span
            - if i.can_activate?
              %a{:href => trigger_state_event_employee_company_invoice_path(i.company, i, {event: :activate}),
                 :data => {:method => :put, :confirm => t(:sure)},
                 :title => ::Company::Invoice.human_state_event_name(:activate)}
                %i.icon-share-alt
            - if i.can_archive?
              %a{:href => trigger_state_event_employee_company_invoice_path(i.company, i, {event: :archive}),
                 :data => {:method => :put, :confirm => t(:sure)},
                 :title => ::Company::Invoice.human_state_event_name(:archive)}
                %i.icon-briefcase
            - if i.can_del?
              %a{:href => trigger_state_event_employee_company_invoice_path(i.company, i, {event: :del}),
                 :data => {:method => :put, :confirm => t(:sure)},
                 :title => ::Company::Invoice.human_state_event_name(:del)}
                %i.icon-remove
      - if i.notes.present?
        %tr
          %td{"colspan" => 11}
            %b= t('.last_note')
            = i.notes.first.short_body
.form-actions
  = render "web/shared/toolbar", {:collection => @companies_invoices, :buttons =>[{:link_title => t('.add_company_invoice'), :link_path => new_employee_companies_invoice_path}]}

app/views/web/employee/companies_invoices/new.html.haml
.span11
  = render 'form', {:url => employee_companies_invoices_path, :legend => t(".new_company_invoice")}